apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example-filter
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: example-filter
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              vm_config:
                code:
                  remote:
                    http_uri:
                      uri: https://storage.googleapis.com/istio-ecosystem/wasm-extensions/example.wasm
                      cluster: google-storage
                      timeout: 10s
                    retry_policy:
                      num_retries: 5
                      retry_back_off:
                        base_interval: 1s
                        max_interval: 3s
                    sha256: a96aacb4fa8fd81bb7a7112b1d46432ec1463b8142d320bc269533832aa3d9a7
                runtime: envoy.wasm.runtime.v8
