apiVersion: v1
kind: ConfigMap
metadata:
  name: example-policy
  namespace: istio-system
data:
  opa_rule.rego: |
    package test

    default allow = false

    allow = true {
      input.request_method == "GET"
      input.destination_workload == "istio-ingressgateway"
      input.request_url_path == "/status/200"
    }

    allow = true {
      input.request_method == "GET"
      input.destination_workload == "istio-ingressgateway"
      input.request_url_path == "/headers"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: istio-system
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: example-policy
      volumes:
      - name: example-policy
        configMap:
          name: example-policy
---
kind: Service
apiVersion: v1
metadata:
  name: opa
  namespace: istio-system
  labels:
    app: opa
spec:
  type: NodePort
  selector:
    app: opa
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
