apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: basic-auth-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
      proxy:
        proxyVersion: ^1\.8.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: example-filter
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "basic_auth_rules": [
                      {
                        "prefix": "/",
                        "request_methods": ["GET", "POST"],
                        "credentials": [
                          "ok:test",
                          "admin:admin",
                          "admin2:admin2"
                        ]
                      }
                    ]
                  }
              vm_config:
                vm_id: basic_auth
                code:
                  remote:
                    http_uri:
                      uri: https://storage.googleapis.com/istio-ecosystem/wasm-extensions/basic-auth/1.8.0.wasm
                      cluster: google-storage
                      timeout: 10s
                    sha256: 707e29db817f76c974d7ce1fe2f61ad64c88856c7ddba99a36fe95439bfe1281
                    retry_policy:
                      num_retries: 5
                      retry_back_off:
                        base_interval: 1s
                        max_interval: 3s
                runtime: envoy.wasm.runtime.v8
