name: Format

on:

  pull_request:
    branches:
    - master
    - release-[0-9]+.[0-9]+

  push:
    branches:
    - master
    - release-[0-9]+.[0-9]+

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Format (clang-format)
      run: |
        sudo apt-get install clang-format-10
        find . -name "*.h" -o -name "*.cc" -o -name "*.proto" | grep -v ".pb." | xargs -n1 clang-format-10 -i
        git diff --exit-code
