name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
      - name: Download artifacts
        run: |
          COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          gsutil cp gs://istio-ecosystem/wasm-extensions/basic-auth/${COMMIT}.wasm basic-auth.wasm
          gsutil cp gs://istio-ecosystem/wasm-extensions/example/${COMMIT}.wasm example.wasm
          # Also prepare an Wasm extension dir for GCS uploading.
          mkdir -p wasm-extensions/basic-auth
          mkdir -p wasm-extensions/example
          GITHUB_TAG_REF=${{ github.ref }}
          cp basic-auth.wasm wasm-extensions/basic-auth/${GITHUB_TAG_REF##*/}.wasm
          cp example.wasm wasm-extensions/example/${GITHUB_TAG_REF##*/}.wasm
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Basic Auth Release Asset
        id: upload-basic-auth-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./basic-auth.wasm
          asset_name: basic-auth.wasm
          asset_content_type: application/wasm
      - name: Upload Example Release Asset
        id: upload-example-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./example.wasm
          asset_name: example.wasm
          asset_content_type: application/wasm
      - name: Upload Modules
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          path: wasm-extensions/
          destination: istio-ecosystem
          credentials: ${{ secrets.WASM_UPLOAD_CRED }}
