name: Test

on:

  pull_request:
    branches:
    - master

  push:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.2'

    - name: Build file format (buildifier)
      run: |
        go get -u github.com/bazelbuild/buildtools/buildifier
        export PATH=$PATH:$(go env GOPATH)/bin
        find . -name "BUILD" | xargs -n1 buildifier -mode=check

    - name: Build
      run: |
        for target in $(bazel query ...); do
          if [[ "{$target}" == *":_wasm_"* ]]; then
            # skip wasm transition target
            continue
          fi
          "${GITHUB_WORKSPACE}/bin/bazel" build "${target}"
        done

    - name: Unit Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Integration Test
      run: |
        go test ./...
